### PR TITLE
#7 Added Appveyor CI configuration

### PR DESCRIPTION
**Pull request by zabrowarnyrafal**

### CODE REVIEW

**Comment by marcinbudny** [comment]
My suggestion is to push packages built from develop and feature branches to a dedicated myget feed.  Packages built from a tag on master can be either pushed automatically to nuget.org or they can be moved from myget to nuget.org by hand.

**Comment by zabrowarnyrafal** [comment]
Done:
* setup for automatically creation of github release draft (no artifacts; we should include release notes)
* setup for deploy to  nuget.org feed

**Comment by marcinbudny** [comment]
What about the myget prerelease deploys?
What about deploying nuget package only for tags on master?

**Comment by zabrowarnyrafal** [comment]
Now each accepted change on master means 'ready to install' version (tagged & release draft); it is stable version (according to version number) - IMO this is enough for now. We follow gitflow workflow so direct commits to master are forbidden (we must set apropriate policies in GH branch settings ) and with support/ release/ hotfix/ branche we have staging phase when we can check quality of changes. IMO there will  be no commits on master without tags so we also not need 'only for tag commits' appveyor setting.

Regarding prerelease packages - IMO we should only publish those which origin from release/support/hotfix branches (-beta prefixed). 
I was considering if myget feed is needed as appveyor provide also feed for published artifacts; if You still thinking that myget feed usgae would be better, please right comment below confirming it and then I will prepare another deploy for beta channel

**Comment by marcinbudny** [comment]
Prerelease also means new features. But we can skip this for now as you suggest.

**Review by marcinbudny — APPROVED** [review]

**Comment by marcinbudny** [comment]
Do we also build the PRs? We need that and also enable a check on PR to have a successful build.

**Comment by zabrowarnyrafal** [comment]
PR build is enabled; right, no successful build no merge possibility - i'll manage it

**Pull request merged**
